run_logged "$FEDORY_INSTALL/user/config-seed.sh"
run_logged "$FEDORY_INSTALL/user/bash.sh"
run_logged "$FEDORY_INSTALL/user/theme.sh"
run_logged "$FEDORY_INSTALL/user/chromium.sh"
run_logged "$FEDORY_INSTALL/user/calculator.sh"
run_logged "$FEDORY_INSTALL/user/systemd.sh"
run_logged "$FEDORY_INSTALL/user/git.sh"
run_logged "$FEDORY_INSTALL/user/xcompose.sh"
run_logged "$FEDORY_INSTALL/user/mise-install.sh"
run_logged "$FEDORY_INSTALL/user/source-tools.sh"
run_logged "$FEDORY_INSTALL/user/mise-work.sh"

run_logged "$FEDORY_INSTALL/user/hardware/asus/fix-audio-mixer.sh"
run_logged "$FEDORY_INSTALL/user/hardware/asus/fix-mic.sh"
run_logged "$FEDORY_INSTALL/user/hardware/framework/fix-f13-amd-audio-input.sh"
run_logged "$FEDORY_INSTALL/user/hardware/dell/xps13-text-scaling.sh"
run_logged "$FEDORY_INSTALL/user/hardware/fix-nouveau-cursor.sh"

run_logged "$FEDORY_INSTALL/user/default-keyring.sh"
run_logged "$FEDORY_INSTALL/user/mise.sh"
